sudo: false
os: linux
language: node_js
node_js: '12'
cache:
  directories:
    - ~/.nvm
    - node_modules
install:
  - npm ci
  - npm run lerna:bootstrap
before_script:
  - npm run lerna run prepublish
before_deploy:
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/dvelasquez/d13z-lerna.git" > /dev/null 2>&1
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script: "lerna:release:canary && npm run lerna:publish:canary"
  skip_cleanup: true
  on:
    branch: build/ci
